name: spense
description: "A new Flutter project."
publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Fonts section to include Space Mono
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf # Include both regular and bold versions if needed

  # Assets section for images, etc. If you want to add any image assets, include them here.
  assets:
    - assets/images/ # For images like icons, backgrounds, etc.
