name: spense
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.2.5+1
  flutter_animated_button: ^2.0.4
  font_awesome_icon_class: ^0.0.6
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  intl: ^0.20.2
  flutter_switch: ^0.3.2
  sqflite: ^2.4.1
  http_interceptor: ^2.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.webp"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/appIcon.webp"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/appIcon.webp"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/appIcon.webp"
