class FinanceTips {
  List<String> expenseTips = [
    "1. Track every expense to understand where your money goes.",
    "2. Create a budget and stick to it.",
    "3. Avoid impulse purchases by planning your spending.",
    "4. Differentiate between needs and wants before spending.",
    "5. Use cash or debit cards instead of credit cards to avoid debt.",
    "6. Set spending limits for discretionary categories like entertainment.",
    "7. Avoid lifestyle inflation as your income increases.",
    "8. Regularly review and cut unnecessary subscriptions.",
    "9. Cook at home instead of eating out to save money.",
    "10. Use public transportation or carpool to reduce transportation costs.",
    "11. Avoid buying things just because they're on sale.",
    "12. Plan major purchases in advance to avoid overspending.",
    "13. Use apps or tools to track and manage your expenses.",
    "14. Avoid emotional spending; stick to your budget.",
    "15. Set aside money for irregular expenses like holidays or repairs.",
    "16. Avoid using credit cards for non-essential purchases.",
    "17. Compare prices before making a purchase.",
    "18. Avoid buying brand names when generic alternatives are available.",
    "19. Limit online shopping to avoid unnecessary purchases.",
    "20. Avoid keeping up with others' spending habits.",
    "21. Use coupons or discounts to save on purchases.",
    "22. Avoid late fees by paying bills on time.",
    "23. Avoid unnecessary bank fees by choosing the right accounts.",
    "24. Avoid spending money you don't have.",
    "25. Regularly review your expenses to identify areas to cut back.",
    "26. Avoid buying things you don't need just because they're trendy.",
    "27. Set financial goals to guide your spending decisions.",
    "28. Avoid spending on things that don't align with your priorities.",
    "29. Use a 24-hour rule for non-essential purchases to avoid impulse buys.",
    "30. Avoid spending money to impress others.",
    "31. Avoid unnecessary travel expenses by planning ahead.",
    "32. Avoid buying extended warranties unless absolutely necessary.",
    "33. Avoid spending on things that don't bring long-term value.",
    "34. Avoid spending money on things you can do yourself.",
    "35. Avoid spending on things that don't contribute to your goals.",
    "36. Avoid spending on things that don't make you happy.",
    "37. Avoid spending on things that don't improve your life.",
    "38. Avoid spending on things that don't align with your values.",
    "39. Avoid spending on things that don't provide a good ROI.",
    "40. Avoid spending on things that don't solve a real problem.",
    "41. Avoid spending on things that don't add value to your life.",
    "42. Avoid spending on things that don't help you achieve your goals.",
    "43. Avoid spending on things that don't make you healthier.",
    "44. Avoid spending on things that don't make you smarter.",
    "45. Avoid spending on things that don't make you happier.",
    "46. Avoid spending on things that don't make you more productive.",
    "47. Avoid spending on things that don't make you more fulfilled.",
    "48. Avoid spending on things that don't make you more successful.",
    "49. Avoid spending on things that don't make you more confident.",
    "50. Avoid spending on things that don't make you more content.",
  ];
  List<String> incomeTips = [
    "1. Diversify your income streams to reduce reliance on a single source.",
    "2. Invest in skills that increase your earning potential.",
    "3. Negotiate your salary or rates regularly.",
    "4. Create a budget to track and allocate your income effectively.",
    "5. Save at least 20% of your income for emergencies and investments.",
    "6. Automate your savings to ensure consistency.",
    "7. Avoid lifestyle inflation as your income grows.",
    "8. Invest in assets that generate passive income.",
    "9. Regularly review and optimize your income sources.",
    "10. Take advantage of tax deductions and credits.",
    "11. Start a side hustle to supplement your primary income.",
    "12. Network to uncover new income opportunities.",
    "13. Reinvest a portion of your income into your business or career.",
    "14. Avoid debt that doesn't generate income or value.",
    "15. Set clear financial goals and align your income strategies with them.",
    "16. Track your income and expenses to identify growth opportunities.",
    "17. Learn to say no to low-paying opportunities that waste your time.",
    "18. Use technology to streamline and scale your income sources.",
    "19. Focus on high-income skills like coding, sales, or marketing.",
    "20. Build a personal brand to attract better-paying opportunities.",
    "21. Invest in education that increases your earning potential.",
    "22. Avoid get-rich-quick schemes; focus on sustainable income growth.",
    "23. Leverage compound interest by investing early and consistently.",
    "24. Create multiple streams of passive income.",
    "25. Regularly assess the ROI of your income-generating activities.",
    "26. Avoid over-reliance on unstable income sources.",
    "27. Use windfalls (bonuses, tax refunds) wisely by saving or investing.",
    "28. Build an emergency fund to protect your income stability.",
    "29. Avoid unnecessary risks that could jeopardize your income.",
    "30. Focus on long-term income growth rather than short-term gains.",
    "31. Learn to negotiate better deals and contracts.",
    "32. Stay updated on market trends to identify new income opportunities.",
    "33. Avoid procrastination; take action to grow your income.",
    "34. Build a strong online presence to attract income opportunities.",
    "35. Invest in tools or resources that increase your productivity.",
    "36. Avoid spending income before you earn it.",
    "37. Regularly review your income goals and adjust your strategies.",
    "38. Focus on creating value to increase your income potential.",
    "39. Avoid comparing your income to others; focus on your own growth.",
    "40. Use your skills to create products or services that generate income.",
    "41. Avoid overcommitting to low-value tasks that don't increase income.",
    "42. Invest in relationships that can lead to income opportunities.",
    "43. Stay disciplined with your income goals and strategies.",
    "44. Avoid impulsive decisions that could harm your income stability.",
    "45. Focus on building assets that appreciate over time.",
    "46. Use your time wisely to maximize income-generating activities.",
    "47. Avoid unnecessary expenses that eat into your income.",
    "48. Regularly seek feedback to improve your income-generating skills.",
    "49. Stay adaptable to changes in the job market or economy.",
    "50. Celebrate milestones but stay focused on long-term income growth.",
  ];
}
